spring:
  application:
    name: 'backend-demo'
  datasource:
    url: jdbc:postgresql://localhost:5432/exampledb
    username: root
    password: toor
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
      hibernate:
        ddl-auto: none